version: '3'
services:
  app:
    image: imutafchiev94/studenti:1.0.0
    ports:
      - "3030:3030" # Map port 3030 on the host to port 3030 in the container
    environment:
      - NODE_ENV=production
